[tox]
skipsdist = True
envlist = py311

[common]
deps =  -r../requirements.txt
        -r./requirements.txt

[testenv:lint]
deps =  {[common]deps}
commands =  pylint {posargs:py.test} --max-line-length=120 --disable=C0114

[testenv:pymongo]
deps =  {[common]deps}
commands =  pytest -k pymongo -v --junitxml=pymongo_results.xml

[testenv:endpoints]
deps =  {[common]deps}
commands =  pytest -k endpoints -v --junitxml=endpoints_results.xml